Continue on CI/CD

diff --git a/.github/workflows/github-action-cicd.yml b/.github/workflows/github-action-cicd.yml
--- a/.github/workflows/github-action-cicd.yml
+++ b/.github/workflows/github-action-cicd.yml
@@ -91,6 +91,54 @@ jobs:
           - name: Setup compilers
             run: |
               sudo apt-get install -y gcc-14 g++-14
+          - name: Configure project
+            run: |
+              export CC=gcc-14
+              export CXX=g++-14
+              export VCPKG_ROOT=${{ github.workspace }}/vcpkg
+              max_attempts=3
+              attempt=0
+              success=false
+
+              while [ $success = false ] && [ $attempt -lt $max_attempts ]; do
+                attempt=$((attempt + 1))
+                echo "CMake configure attempt $attempt of $max_attempts"
+
+                if cmake --preset=ci-build; then
+                  success=true
+                  echo "CMake configuration succeeded on attempt $attempt"
+                else
+                  if [ $attempt -eq $max_attempts ]; then
+                    echo "CMake configuration failed after $max_attempts attempts"
+                    exit 1
+                  fi
+                  echo "CMake configuration failed on attempt $attempt. Retrying..."
+                  sleep 5
+                fi
+              done
+          - name: Build project
+            run: |
+              export CC=gcc-14
+              export CXX=g++-14
+              export VCPKG_ROOT=${{ github.workspace }}/vcpkg
+              cmake --build build --parallel 8 --target all
+          - name: Run Tests
+            working-directory: ${{ github.workspace }}/build
+            run: |
+              export CC=gcc-14
+              export CXX=g++-14
+              export VCPKG_ROOT=${{ github.workspace }}/vcpkg
+              ctest --verbose
+            continue-on-error: true
+          - name: Upload test results
+            uses: actions/upload-artifact@v4
+            with:
+              name: test-results
+              path: ${{ github.workspace }}/build/test-results
+          - name: Publish Test Results
+            uses: mikepenz/action-junit-report@v3
+            with:
+              report_paths: '${{ github.workspace }}/build/test-results'
 # -- windows latest runner - msvc
     build-msvc-windows-latest:
         name: Build x64-windows-msvc
